[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
via_ir = true
optimizer = true
optimizer_runs = 200

# 파일 시스템 접근 권한 설정
fs_permissions = [
    { access = "read", path = "./broadcast/" },
    { access = "read", path = "./cache/" },
    { access = "read", path = "./out/" }
]

# See more config options [https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options](https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options)
